name: Build and Deploy Go Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.4"

      - name: Build Binary
        run: |
          go build -o pocketbase ./cmd/main.go

      - name: Deploy to Production
        run: |
          # Move executable to target directory (force overwrite)
          mv -f pocketbase /home/orangepi/pocketbase/pocketbase
          chmod +x /home/orangepi/pocketbase/pocketbase

      - name: Restart Service
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart pocketbase
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl status pocketbase
