name: Build and Deploy Go Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build (GitHub Runner)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.4"

      - name: Build Binary (ARM64)
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o pocketbase ./cmd/main.go

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: pocketbase-binary
          path: pocketbase
          retention-days: 1

  deploy:
    name: Deploy (Self Hosted)
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download Binary
        uses: actions/download-artifact@v4
        with:
          name: pocketbase-binary

      - name: Install & Restart
        run: |
          # The binary is downloaded to the current workspace directory
          # Move it to the target location
          mv -f pocketbase /home/orangepi/pocketbase/pocketbase
          chmod +x /home/orangepi/pocketbase/pocketbase

          echo "Restarting service..."
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart pocketbase
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl status pocketbase
